
-- 1. SELECTION (행 선택)
SELECT * FROM 
KOPO_PRODUCT_VOLUME;

-- 2. PROJECTION (컬럼 선택)
SELECT PRODUCTGROUP FROM
KOPO_PRODUCT_VOLUME;

-- 3. UNION (데이터 합치기, 합칠 데이터의 컬럼 수가 똑같아야 한다)
SELECT 
    REGIONID,
    PRODUCTGROUP,
    YEARWEEK,
    VOLUME 
    FROM KOPO_PRODUCT_VOLUME_A01
UNION
SELECT 
    REGIONID,
    PRODUCTGROUP,
    YEARWEEK,
    VOLUME 
    FROM KOPO_PRODUCT_VOLUME_A02;

-- DATA SELECT
-- EXPRESSION Example 
SELECT
    'D516' AS MEASUREID,
    3*4 AS CALCULATION,
    REGIONID||PRODUCTGROUP||YEARWEEK AS KEY,
    CONCAT(REGIONID, CONCAT(PRODUCTGROUP, YEARWEEK)) AS TEST,
    REGIONID,
    PRODUCTGROUP,
    YEARWEEK,
    VOLUME
FROM KOPO_PRODUCT_VOLUME;

-- 실습 #1
-- 1,395,992 건
SELECT REGIONID, QTY
FROM
(
    SELECT *  FROM KOPO_CHANNEL_RESULT_A01
    UNION 
    SELECT *  FROM KOPO_CHANNEL_RESULT_A02
);

-- 8614건
SELECT REGIONID, QTY FROM KOPO_CHANNEL_RESULT_A01
UNION 
SELECT REGIONID, QTY FROM KOPO_CHANNEL_RESULT_A02;

-- 생각해볼 문제 #1
SELECT A.REGIONID,
    A.REGIONNAME,
    A.AP1ID,
    A.AP1NAME,
    A.ACCOUNTID,
    A.ACCOUNTNAME,
    A.SALESID,
    A.SALESNAME,
    A.PRODUCTGROUP,
    A.PRODUCT,
    (SELECT B.PRODUCT_NAME 
        FROM KOPO_PRODUCT_MST B 
        WHERE 1=1
        AND A.PRODUCT = B.PRODUCT_ID) AS PRODUCT_NAME,
    A.ITEM,
    A.YEARWEEK,
    A.YEAR,
    A.WEEK,
    A.QTY,
    A.TARGET,
    A.IDX 
FROM 
KOPO_CHANNEL_RESULT_A01 A;

SELECT A.REGIONID,
    A.REGIONNAME,
    A.AP1ID,
    A.AP1NAME,
    A.ACCOUNTID,
    A.ACCOUNTNAME,
    A.SALESID,
    A.SALESNAME,
    A.PRODUCTGROUP,
    A.PRODUCT,
    B.PRODUCT_NAME,
    A.ITEM,
    A.YEARWEEK,
    A.YEAR,
    A.WEEK,
    A.QTY,
    A.TARGET,
    A.IDX 
FROM 
KOPO_CHANNEL_RESULT_A01 A,
KOPO_PRODUCT_MST B
WHERE 1=1
AND A.PRODUCT = B.PRODUCT_ID(+);

SELECT A.REGIONID,
    A.REGIONNAME,
    A.AP1ID,
    A.AP1NAME,
    A.ACCOUNTID,
    A.ACCOUNTNAME,
    A.SALESID,
    A.SALESNAME,
    A.PRODUCTGROUP,
    A.PRODUCT,
    B.PRODUCT_NAME,
    A.ITEM,
    A.YEARWEEK,
    A.YEAR,
    A.WEEK,
    A.QTY,
    A.TARGET,
    A.IDX 
FROM 
KOPO_CHANNEL_RESULT_A01 A
LEFT JOIN KOPO_PRODUCT_MST B
ON A.PRODUCT = B.PRODUCT_ID;








SELECT * FROM TABS
WHERE 1=1
AND TABLE_NAME LIKE '%MST%'




